namespace NCS.DSS.ChangeFeedListener.Model
{
    public class ChangeFeedListenerConfigurationSettings
    {
        public string ActionCollectionId { get; set; }
        public string ActionDatabaseId { get; set; }
        public string ActionLeaseCollectionName { get; set; }
        public string ActionLeaseCollectionPrefix { get; set; }
        public string ActionPlanCollectionId { get; set; }
        public string ActionPlanDatabaseId { get; set; }
        public string ActionPlanLeaseCollectionName { get; set; }
        public string ActionPlanLeaseCollectionPrefix { get; set; }
        public string AddressCollectionId { get; set; }
        public string AddressDatabaseId { get; set; }
        public string AddressLeaseCollectionName { get; set; }
        public string AddressLeaseCollectionPrefix { get; set; }
        public string AdviserDetailCollectionId { get; set; }
        public string AdviserDetailDatabaseId { get; set; }
        public string AdviserDetailLeaseCollectionName { get; set; }
        public string AdviserDetailLeaseCollectionPrefix { get; set; }
        public string APPINSIGHTS_INSTRUMENTATIONKEY { get; set; }
        public string AzureWebJobsStorage { get; set; }
        public string ChangeFeedQueueName { get; set; }
        public string ContactCollectionId { get; set; }
        public string ContactDatabaseId { get; set; }
        public string ContactLeaseCollectionName { get; set; }
        public string ContactLeaseCollectionPrefix { get; set; }
        public string CosmosDBConnectionString { get; set; }
        public string CustomerCollectionId { get; set; }
        public string CustomerDatabaseId { get; set; }
        public string CustomerLeaseCollectionName { get; set; }
        public string CustomerLeaseCollectionPrefix { get; set; }
        public string CustomerSearchIndexName { get; set; }
        public string CustomerSearchIndexNameV2 { get; set; }
        public string DataCollectionsCollectionId { get; set; }
        public string DataCollectionsDatabaseId { get; set; }
        public string DataCollectionsLeaseCollectionName { get; set; }
        public string DataCollectionsLeaseCollectionPrefix { get; set; }
        public string DiversityCollectionId { get; set; }
        public string DiversityDatabaseId { get; set; }
        public string DiversityLeaseCollectionName { get; set; }
        public string DiversityLeaseCollectionPrefix { get; set; }
        public string EmploymentProgressionCollectionId { get; set; }
        public string EmploymentProgressionDatabaseId { get; set; }
        public string EmploymentProgressionLeaseCollectionName { get; set; }
        public string EmploymentProgressionLeaseCollectionPrefix { get; set; }
        public string FUNCTIONS_EXTENSION_VERSION { get; set; }
        public string FUNCTIONS_WORKER_RUNTIME { get; set; }
        public string GoalCollectionId { get; set; }
        public string GoalDatabaseId { get; set; }
        public string GoalLeaseCollectionName { get; set; }
        public string GoalLeaseCollectionPrefix { get; set; }
        public string InteractionCollectionId { get; set; }
        public string InteractionDatabaseId { get; set; }
        public string InteractionLeaseCollectionName { get; set; }
        public string InteractionLeaseCollectionPrefix { get; set; }
        public string LearningProgressionCollectionId { get; set; }
        public string LearningProgressionDatabaseId { get; set; }
        public string LearningProgressionLeaseCollectionName { get; set; }
        public string LearningProgressionLeaseCollectionPrefix { get; set; }
        public string MSDEPLOY_RENAME_LOCKED_FILES { get; set; }
        public string OutcomeCollectionId { get; set; }
        public string OutcomeDatabaseId { get; set; }
        public string OutcomeLeaseCollectionName { get; set; }
        public string OutcomeLeaseCollectionPrefix { get; set; }
        public string SearchServiceAdminApiKey { get; set; }
        public string SearchServiceName { get; set; }
        public string ServiceBusConnectionString { get; set; }
        public string SessionCollectionId { get; set; }
        public string SessionDatabaseId { get; set; }
        public string SessionLeaseCollectionName { get; set; }
        public string SessionLeaseCollectionPrefix { get; set; }
        public string SubscriptionCollectionId { get; set; }
        public string SubscriptionDatabaseId { get; set; }
        public string SubscriptionLeaseCollectionName { get; set; }
        public string SubscriptionLeaseCollectionPrefix { get; set; }
        public string TransferCollectionId { get; set; }
        public string TransferDatabaseId { get; set; }
        public string TransferLeaseCollectionName { get; set; }
        public string TransferLeaseCollectionPrefix { get; set; }
        public string WebChatCollectionId { get; set; }
        public string WebChatDatabaseId { get; set; }
        public string WebChatLeaseCollectionName { get; set; }
        public string WebChatLeaseCollectionPrefix { get; set; }
    }
}
