variables:
    SolutionBaseName: 'NCS.DSS.ChangeFeedListener'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.16.4
    endpoint: 'GitHub (CDH)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio
jobs:
- job: BuildDotNetStandard
  displayName: Build-DotNetStandard
  
  steps:
  - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcorefunctionapp-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
      GitVersionVersion: 5.12.x
      DotNetCoreVersion: 8.x