variables:
  SolutionBaseName: 'NCS.DSS.ChangeFeedListener'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

jobs:
- job:
  displayName: Build-DotNetStandard
  workspace:
    clean: all
  steps:
   - task: gittools.gitversion.gitversion-task.GitVersion@4
     displayName: GitVersion
     inputs:
       preferBundledVersion: false
   - task: NuGetToolInstaller@0
     displayName: 'Use NuGet 4.3.0'
   - task: NuGetCommand@2
     displayName: 'NuGet restore ${{ variables.SolutionBaseName }}.sln'
     inputs:
       restoreSolution: '${{ variables.SolutionBaseName }}.sln'
   - task: DotNetCoreCLI@2
     displayName: 'dotnet build'
     inputs:
       command: 'build'
       projects: '**/NCS.DSS.ChangeFeedListener.csproj'
       arguments: '-o "$(build.artifactstagingdirectory)\DeploymentPackages\\"'
   - task: ArchiveFiles@2
     displayName: 'Archive $(build.artifactstagingdirectory)\DeploymentPackages\'
     inputs:
      rootFolderOrFile: '$(build.artifactstagingdirectory)\DeploymentPackages\'
      includeRootFolder: false
      archiveFile: '$(build.artifactstagingdirectory)\DeploymentPackages\$(SolutionBaseName).zip'
   - task: CopyFiles@2
     displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Azure'
     inputs:
       sourceFolder: 'Resources'
       contents: '**'
       targetFolder: '$(build.artifactstagingdirectory)/Azure'
   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: ${{ variables.SolutionBaseName }}'
     inputs:
       pathtoPublish: $(build.artifactstagingdirectory)
       artifactName: ${{ variables.SolutionBaseName }}
       publishLocation: container